=== jcmachadoh/cuba-deportes-data/schemas/v1/standings.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "Clasificación",
 "type": "object",
 "required": [
  "schemaVersion",
  "type",
  "id",
  "competitionId",
  "season",
  "groups"
 ],
 "properties": {
  "schemaVersion": {
   "const": 1
  },
  "type": {
   "type": "string"
  },
  "id": {
   "type": "string"
  },
  "updatedAt": {
   "type": "string"
  },
  "sources": {
   "type": "array",
   "items": {
    "type": "string"
   }
  },
  "competitionId": {
   "type": "string"
  },
  "season": {
   "type": "string"
  },
  "groups": {
   "type": "array",
   "items": {
    "type": "object",
    "required": [
     "id",
     "name",
     "rows"
    ],
    "properties": {
     "rows": {
      "type": "array",
      "items": {
       "$ref": "#/$defs/row"
      }
     }
    }
   }
  }
 },
 "additionalProperties": true,
 "$defs": {
  "personSummary": {
   "type": "object",
   "required": [
    "id",
    "name"
   ],
   "properties": {
    "id": {
     "type": "string",
     "pattern": "^p\\."
    },
    "name": {
     "type": "object",
     "required": [
      "full"
     ],
     "properties": {
      "full": {
       "type": "string"
      },
      "first": {
       "type": "string"
      },
      "last": {
       "type": "string"
      },
      "short": {
       "type": "string"
      },
      "abbrev": {
       "type": "string"
      }
     }
    },
    "birthDate": {
     "type": "string"
    },
    "nationalities": {
     "type": "array",
     "items": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
     }
    },
    "isCuban": {
     "type": "boolean"
    },
    "birthCountry": {
     "type": "string",
     "pattern": "^[A-Z]{2}$"
    },
    "photo": {
     "$ref": "#/$defs/photo"
    }
   }
  },
  "photo": {
   "type": "object",
   "required": [
    "url"
   ],
   "properties": {
    "url": {
     "type": "string"
    },
    "credit": {
     "type": "string"
    },
    "license": {
     "type": "string"
    },
    "source": {
     "type": "string"
    }
   }
  },
  "row": {
   "type": "object",
   "required": [
    "participantId",
    "participantType",
    "stats"
   ],
   "properties": {
    "participantId": {
     "type": "string"
    },
    "participantType": {
     "enum": [
      "team",
      "person"
     ]
    },
    "rank": {
     "type": [
      "integer",
      "null"
     ]
    },
    "stats": {
     "type": "object",
     "additionalProperties": {
      "type": [
       "number",
       "string",
       "null"
      ]
     }
    },
    "extra": {
     "type": "object"
    },
    "person": {
     "$ref": "#/$defs/personSummary"
    }
   }
  },
  "name": {
   "type": "object",
   "required": [
    "full"
   ],
   "properties": {
    "full": {
     "type": "string"
    },
    "first": {
     "type": "string"
    },
    "last": {
     "type": "string"
    },
    "short": {
     "type": "string"
    },
    "abbrev": {
     "type": "string"
    }
   }
  }
 }
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/soccer.mex-1/seasons/2026-27/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "soccer.mex-1:2026-27",
 "updatedAt": "2026-10-18T04:31:50Z",
 "sources": [
  "espn"
 ],
 "competitionId": "soccer.mex-1",
 "season": "2026-27",
 "groups": [
  {
   "id": "1",
   "name": "2026 Torneo Apertura",
   "rows": [
    {
     "participantId": "soccer.america",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 11,
      "W": 7,
      "D": 3,
      "L": 1,
      "GF": 27,
      "GA": 14,
      "GD": 13,
      "PTS": 24
     }
    },
    {
     "participantId": "soccer.toluca",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 12,
      "W": 6,
      "D": 3,
      "L": 3,
      "GF": 26,
      "GA": 16,
      "GD": 10,
      "PTS": 21
     }
    },
    {
     "participantId": "soccer.atlas",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 12,
      "W": 6,
      "D": 3,
      "L": 3,
      "GF": 19,
      "GA": 18,
      "GD": 1,
      "PTS": 21
     }
    },
    {
     "participantId": "soccer.guadalajara",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 12,
      "W": 5,
      "D": 5,
      "L": 2,
      "GF": 19,
      "GA": 12,
      "GD": 7,
      "PTS": 20
     }
    },
    {
     "participantId": "soccer.queretaro",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 11,
      "W": 6,
      "D": 2,
      "L": 3,
      "GF": 15,
      "GA": 13,
      "GD": 2,
      "PTS": 20
     }
    },
    {
     "participantId": "soccer.leon",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 12,
      "W": 5,
      "D": 3,
      "L": 4,
      "GF": 18,
      "GA": 17,
      "GD": 1,
      "PTS": 18
     }
    },
    {
     "participantId": "soccer.cruz-azul",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 11,
      "W": 5,
      "D": 2,
      "L": 4,
      "GF": 22,
      "GA": 21,
      "GD": 1,
      "PTS": 17
     }
    },
    {
     "participantId": "soccer.santos",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 12,
      "W": 5,
      "D": 1,
      "L": 6,
      "GF": 17,
      "GA": 16,
      "GD": 1,
      "PTS": 16
     }
    },
    {
     "participantId": "soccer.tijuana",
     "participantType": "team",
     "rank": 9,
     "stats": {
      "GP": 11,
      "W": 4,
      "D": 4,
      "L": 3,
      "GF": 15,
      "GA": 14,
      "GD": 1,
      "PTS": 16
     }
    },
    {
     "participantId": "soccer.pumas-unam",
     "participantType": "team",
     "rank": 10,
     "stats": {
      "GP": 12,
      "W": 4,
      "D": 4,
      "L": 4,
      "GF": 19,
      "GA": 20,
      "GD": -1,
      "PTS": 16
     }
    },
    {
     "participantId": "soccer.puebla",
     "participantType": "team",
     "rank": 11,
     "stats": {
      "GP": 12,
      "W": 4,
      "D": 4,
      "L": 4,
      "GF": 12,
      "GA": 13,
      "GD": -1,
      "PTS": 16
     }
    },
    {
     "participantId": "soccer.monterrey",
     "participantType": "team",
     "rank": 12,
     "stats": {
      "GP": 10,
      "W": 4,
      "D": 2,
      "L": 4,
      "GF": 17,
      "GA": 15,
      "GD": 2,
      "PTS": 14
     }
    },
    {
     "participantId": "soccer.tigres-uanl",
     "participantType": "team",
     "rank": 13,
     "stats": {
      "GP": 12,
      "W": 3,
      "D": 5,
      "L": 4,
      "GF": 14,
      "GA": 16,
      "GD": -2,
      "PTS": 14
     }
    },
    {
     "participantId": "soccer.pachuca",
     "participantType": "team",
     "rank": 14,
     "stats": {
      "GP": 11,
      "W": 3,
      "D": 4,
      "L": 4,
      "GF": 18,
      "GA": 14,
      "GD": 4,
      "PTS": 13
     }
    },
    {
     "participantId": "soccer.atletico-de-san-luis",
     "participantType": "team",
     "rank": 15,
     "stats": {
      "GP": 12,
      "W": 3,
      "D": 4,
      "L": 5,
      "GF": 16,
      "GA": 21,
      "GD": -5,
      "PTS": 13
     }
    },
    {
     "participantId": "soccer.atlante",
     "participantType": "team",
     "rank": 16,
     "stats": {
      "GP": 12,
      "W": 2,
      "D": 5,
      "L": 5,
      "GF": 13,
      "GA": 19,
      "GD": -6,
      "PTS": 11
     }
    },
    {
     "participantId": "soccer.necaxa",
     "participantType": "team",
     "rank": 17,
     "stats": {
      "GP": 12,
      "W": 2,
      "D": 3,
      "L": 7,
      "GF": 15,
      "GA": 25,
      "GD": -10,
      "PTS": 9
     }
    },
    {
     "participantId": "soccer.fc-juarez",
     "participantType": "team",
     "rank": 18,
     "stats": {
      "GP": 11,
      "W": 1,
      "D": 1,
      "L": 9,
      "GF": 8,
      "GA": 26,
      "GD": -18,
      "PTS": 4
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.lmb/seasons/2022/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.lmb:2022",
 "updatedAt": "2026-10-03T18:06:46Z",
 "sources": [
  "mlb-statsapi"
 ],
 "competitionId": "baseball.lmb",
 "season": "2022",
 "groups": [
  {
   "id": "222",
   "name": "Mexican League Norte",
   "rows": [
    {
     "participantId": "baseball.toros-de-tijuana",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 90,
      "W": 62,
      "L": 28,
      "PCT": 0.689,
      "GB": -19.0,
      "STRK": "W2",
      "L10": "7-3",
      "HOME": "31-14",
      "AWAY": "31-14",
      "RS": 624,
      "RA": 384,
      "RD": 240
     },
     "extra": {
      "leagueRank": "1"
     }
    },
    {
     "participantId": "baseball.tecos-de-los-dos-laredos",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 86,
      "W": 59,
      "L": 27,
      "PCT": 0.686,
      "GB": -18.0,
      "STRK": "W2",
      "L10": "9-1",
      "HOME": "35-10",
      "AWAY": "24-17",
      "RS": 460,
      "RA": 349,
      "RD": 111
     },
     "extra": {
      "leagueRank": "2"
     }
    },
    {
     "participantId": "baseball.acereros-del-norte",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 85,
      "W": 54,
      "L": 31,
      "PCT": 0.635,
      "GB": -13.5,
      "STRK": "W9",
      "L10": "9-1",
      "HOME": "30-15",
      "AWAY": "24-16",
      "RS": 622,
      "RA": 448,
      "RD": 174
     },
     "extra": {
      "leagueRank": "3"
     }
    },
    {
     "participantId": "baseball.sultanes-de-monterrey-2",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 90,
      "W": 51,
      "L": 39,
      "PCT": 0.567,
      "GB": -8.0,
      "STRK": "L1",
      "L10": "4-6",
      "HOME": "28-17",
      "AWAY": "23-22",
      "RS": 523,
      "RA": 482,
      "RD": 41
     },
     "extra": {
      "leagueRank": "5"
     }
    },
    {
     "participantId": "baseball.algodoneros-union-laguna",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 88,
      "W": 48,
      "L": 40,
      "PCT": 0.545,
      "GB": -6.0,
      "STRK": "L2",
      "L10": "6-4",
      "HOME": "21-22",
      "AWAY": "27-18",
      "RS": 535,
      "RA": 504,
      "RD": 31
     },
     "extra": {
      "leagueRank": "8"
     }
    },
    {
     "participantId": "baseball.rieleros-de-aguascalientes",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 88,
      "W": 42,
      "L": 46,
      "PCT": 0.477,
      "STRK": "L2",
      "L10": "3-7",
      "HOME": "20-25",
      "AWAY": "22-21",
      "RS": 562,
      "RA": 546,
      "RD": 16
     },
     "extra": {
      "leagueRank": "11"
     }
    },
    {
     "participantId": "baseball.saraperos-de-saltillo",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 90,
      "W": 38,
      "L": 52,
      "PCT": 0.422,
      "GB": 5.0,
      "STRK": "L9",
      "L10": "1-9",
      "HOME": "24-21",
      "AWAY": "14-31",
      "RS": 629,
      "RA": 688,
      "RD": -59
     },
     "extra": {
      "leagueRank": "13"
     }
    },
    {
     "participantId": "baseball.caliente-de-durango",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 90,
      "W": 37,
      "L": 53,
      "PCT": 0.411,
      "GB": 6.0,
      "STRK": "W1",
      "L10": "4-6",
      "HOME": "23-22",
      "AWAY": "14-31",
      "RS": 612,
      "RA": 677,
      "RD": -65
     },
     "extra": {
      "leagueRank": "14"
     }
    },
    {
     "participantId": "baseball.mariachis-de-guadalajara",
     "participantType": "team",
     "rank": 9,
     "stats": {
      "GP": 90,
      "W": 33,
      "L": 57,
      "PCT": 0.367,
      "GB": 10.0,
      "STRK": "W1",
      "L10": "2-8",
      "HOME": "19-26",
      "AWAY": "14-31",
      "RS": 573,
      "RA": 661,
      "RD": -88
     },
     "extra": {
      "leagueRank": "16"
     }
    }
   ]
  },
  {
   "id": "223",
   "name": "Mexican League Sur",
   "rows": [
    {
     "participantId": "baseball.diablos-rojos-del-mexico",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 84,
      "W": 50,
      "L": 34,
      "PCT": 0.595,
      "GB": -11.5,
      "STRK": "W6",
      "L10": "9-1",
      "HOME": "29-12",
      "AWAY": "21-22",
      "RS": 614,
      "RA": 530,
      "RD": 84
     },
     "extra": {
      "leagueRank": "4"
     }
    },
    {
     "participantId": "baseball.olmecas-de-tabasco",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 84,
      "W": 47,
      "L": 37,
      "PCT": 0.56,
      "GB": -8.5,
      "STRK": "W6",
      "L10": "6-4",
      "HOME": "25-14",
      "AWAY": "22-23",
      "RS": 437,
      "RA": 397,
      "RD": 40
     },
     "extra": {
      "leagueRank": "6"
     }
    },
    {
     "participantId": "baseball.pericos-de-puebla",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 87,
      "W": 48,
      "L": 39,
      "PCT": 0.552,
      "GB": -8.0,
      "STRK": "L3",
      "L10": "7-3",
      "HOME": "26-16",
      "AWAY": "22-23",
      "RS": 546,
      "RA": 483,
      "RD": 63
     },
     "extra": {
      "leagueRank": "7"
     }
    },
    {
     "participantId": "baseball.leones-de-yucatan",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 89,
      "W": 46,
      "L": 43,
      "PCT": 0.517,
      "GB": -5.0,
      "STRK": "W5",
      "L10": "7-3",
      "HOME": "26-19",
      "AWAY": "20-24",
      "RS": 495,
      "RA": 457,
      "RD": 38
     },
     "extra": {
      "leagueRank": "9"
     }
    },
    {
     "participantId": "baseball.tigres-de-quintana-roo",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 90,
      "W": 44,
      "L": 46,
      "PCT": 0.489,
      "GB": -2.5,
      "STRK": "W2",
      "L10": "3-7",
      "HOME": "22-23",
      "AWAY": "22-23",
      "RS": 474,
      "RA": 556,
      "RD": -82
     },
     "extra": {
      "leagueRank": "10"
     }
    },
    {
     "participantId": "baseball.el-aguila-de-veracruz",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 89,
      "W": 41,
      "L": 48,
      "PCT": 0.461,
      "STRK": "L2",
      "L10": "4-6",
      "HOME": "23-22",
      "AWAY": "18-26",
      "RS": 433,
      "RA": 481,
      "RD": -48
     },
     "extra": {
      "leagueRank": "12"
     }
    },
    {
     "participantId": "baseball.guerreros-de-oaxaca",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 87,
      "W": 34,
      "L": 53,
      "PCT": 0.391,
      "GB": 6.0,
      "STRK": "L4",
      "L10": "3-7",
      "HOME": "23-22",
      "AWAY": "11-31",
      "RS": 533,
      "RA": 606,
      "RD": -73
     },
     "extra": {
      "leagueRank": "15"
     }
    },
    {
     "participantId": "baseball.piratas-de-campeche",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 87,
      "W": 29,
      "L": 58,
      "PCT": 0.333,
      "GB": 11.0,
      "STRK": "L7",
      "L10": "1-9",
      "HOME": "14-28",
      "AWAY": "15-30",
      "RS": 414,
      "RA": 583,
      "RD": -169
     },
     "extra": {
      "leagueRank": "17"
     }
    },
    {
     "participantId": "baseball.bravos-de-leon",
     "participantType": "team",
     "rank": 9,
     "stats": {
      "GP": 90,
      "W": 29,
      "L": 61,
      "PCT": 0.322,
      "GB": 12.5,
      "STRK": "L1",
      "L10": "3-7",
      "HOME": "18-27",
      "AWAY": "11-34",
      "RS": 512,
      "RA": 766,
      "RD": -254
     },
     "extra": {
      "leagueRank": "18"
     }
    }
   ]
  }
 ]
}
