=== jcmachadoh/cuba-deportes-data/schemas/v1/standings.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "Clasificación",
 "type": "object",
 "required": [
  "schemaVersion",
  "type",
  "id",
  "competitionId",
  "season",
  "groups"
 ],
 "properties": {
  "schemaVersion": {
   "const": 1
  },
  "type": {
   "type": "string"
  },
  "id": {
   "type": "string"
  },
  "updatedAt": {
   "type": "string"
  },
  "sources": {
   "type": "array",
   "items": {
    "type": "string"
   }
  },
  "competitionId": {
   "type": "string"
  },
  "season": {
   "type": "string"
  },
  "groups": {
   "type": "array",
   "items": {
    "type": "object",
    "required": [
     "id",
     "name",
     "rows"
    ],
    "properties": {
     "rows": {
      "type": "array",
      "items": {
       "$ref": "#/$defs/row"
      }
     }
    }
   }
  }
 },
 "additionalProperties": true,
 "$defs": {
  "personSummary": {
   "type": "object",
   "required": [
    "id",
    "name"
   ],
   "properties": {
    "id": {
     "type": "string",
     "pattern": "^p\\."
    },
    "name": {
     "type": "object",
     "required": [
      "full"
     ],
     "properties": {
      "full": {
       "type": "string"
      },
      "first": {
       "type": "string"
      },
      "last": {
       "type": "string"
      },
      "short": {
       "type": "string"
      },
      "abbrev": {
       "type": "string"
      }
     }
    },
    "birthDate": {
     "type": "string"
    },
    "nationalities": {
     "type": "array",
     "items": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
     }
    },
    "isCuban": {
     "type": "boolean"
    },
    "birthCountry": {
     "type": "string",
     "pattern": "^[A-Z]{2}$"
    },
    "photo": {
     "$ref": "#/$defs/photo"
    }
   }
  },
  "photo": {
   "type": "object",
   "required": [
    "url"
   ],
   "properties": {
    "url": {
     "type": "string"
    },
    "credit": {
     "type": "string"
    },
    "license": {
     "type": "string"
    },
    "source": {
     "type": "string"
    }
   }
  },
  "row": {
   "type": "object",
   "required": [
    "participantId",
    "participantType",
    "stats"
   ],
   "properties": {
    "participantId": {
     "type": "string"
    },
    "participantType": {
     "enum": [
      "team",
      "person"
     ]
    },
    "rank": {
     "type": [
      "integer",
      "null"
     ]
    },
    "stats": {
     "type": "object",
     "additionalProperties": {
      "type": [
       "number",
       "string",
       "null"
      ]
     }
    },
    "extra": {
     "type": "object"
    },
    "person": {
     "$ref": "#/$defs/personSummary"
    }
   }
  },
  "name": {
   "type": "object",
   "required": [
    "full"
   ],
   "properties": {
    "full": {
     "type": "string"
    },
    "first": {
     "type": "string"
    },
    "last": {
     "type": "string"
    },
    "short": {
     "type": "string"
    },
    "abbrev": {
     "type": "string"
    }
   }
  }
 }
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.npb/seasons/2025/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.npb:2025",
 "updatedAt": "2026-10-03T18:08:24Z",
 "sources": [
  "npb"
 ],
 "competitionId": "baseball.npb",
 "season": "2025",
 "groups": [
  {
   "id": "central",
   "name": "Liga Central",
   "rows": [
    {
     "participantId": "baseball.hanshin-tigers",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 143,
      "W": 85,
      "L": 54,
      "T": 4,
      "PCT": 0.612,
      "HOME": "41-29",
      "AWAY": "44-25"
     }
    },
    {
     "participantId": "baseball.yokohama-dena-baystars",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 143,
      "W": 71,
      "L": 66,
      "T": 6,
      "PCT": 0.518,
      "GB": 13.0,
      "HOME": "36-32",
      "AWAY": "35-34"
     }
    },
    {
     "participantId": "baseball.yomiuri-giants",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 143,
      "W": 70,
      "L": 69,
      "T": 4,
      "PCT": 0.504,
      "GB": 15.0,
      "HOME": "44-26",
      "AWAY": "26-43"
     }
    },
    {
     "participantId": "baseball.chunichi-dragons",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 143,
      "W": 63,
      "L": 78,
      "T": 2,
      "PCT": 0.447,
      "GB": 23.0,
      "HOME": "35-36",
      "AWAY": "28-42"
     }
    },
    {
     "participantId": "baseball.hiroshima-toyo-carp",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 143,
      "W": 59,
      "L": 79,
      "T": 5,
      "PCT": 0.428,
      "GB": 25.5,
      "HOME": "37-32",
      "AWAY": "22-47"
     }
    },
    {
     "participantId": "baseball.tokyo-yakult-swallows",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 143,
      "W": 57,
      "L": 79,
      "T": 7,
      "PCT": 0.419,
      "GB": 26.5,
      "HOME": "32-35",
      "AWAY": "25-44"
     }
    }
   ]
  },
  {
   "id": "pacific",
   "name": "Liga del Pacífico",
   "rows": [
    {
     "participantId": "baseball.fukuoka-softbank-hawks",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 143,
      "W": 87,
      "L": 52,
      "T": 4,
      "PCT": 0.626,
      "HOME": "44-24",
      "AWAY": "43-28"
     }
    },
    {
     "participantId": "baseball.hokkaido-nippon-ham-fighters",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 143,
      "W": 83,
      "L": 57,
      "T": 3,
      "PCT": 0.593,
      "GB": 4.5,
      "HOME": "43-28",
      "AWAY": "40-29"
     }
    },
    {
     "participantId": "baseball.orix-buffaloes",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 143,
      "W": 74,
      "L": 66,
      "T": 3,
      "PCT": 0.529,
      "GB": 13.5,
      "HOME": "38-32",
      "AWAY": "36-34"
     }
    },
    {
     "participantId": "baseball.tohoku-rakuten-golden-eagles",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 143,
      "W": 67,
      "L": 74,
      "T": 2,
      "PCT": 0.475,
      "GB": 21.0,
      "HOME": "35-36",
      "AWAY": "32-38"
     }
    },
    {
     "participantId": "baseball.saitama-seibu-lions",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 143,
      "W": 63,
      "L": 77,
      "T": 3,
      "PCT": 0.45,
      "GB": 24.5,
      "HOME": "35-34",
      "AWAY": "28-43"
     }
    },
    {
     "participantId": "baseball.chiba-lotte-marines",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 143,
      "W": 56,
      "L": 84,
      "T": 3,
      "PCT": 0.4,
      "GB": 31.5,
      "HOME": "33-38",
      "AWAY": "23-46"
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/soccer.bra-1/seasons/2026/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "soccer.bra-1:2026",
 "updatedAt": "2026-10-31T05:44:55Z",
 "sources": [
  "espn"
 ],
 "competitionId": "soccer.bra-1",
 "season": "2026",
 "groups": [
  {
   "id": "1",
   "name": "2026",
   "rows": [
    {
     "participantId": "soccer.flamengo",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 33,
      "W": 22,
      "D": 7,
      "L": 4,
      "GF": 68,
      "GA": 28,
      "GD": 40,
      "PTS": 73
     }
    },
    {
     "participantId": "soccer.palmeiras",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 33,
      "W": 20,
      "D": 10,
      "L": 3,
      "GF": 56,
      "GA": 22,
      "GD": 34,
      "PTS": 70
     }
    },
    {
     "participantId": "soccer.cruzeiro",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 33,
      "W": 17,
      "D": 6,
      "L": 10,
      "GF": 52,
      "GA": 46,
      "GD": 6,
      "PTS": 57
     }
    },
    {
     "participantId": "soccer.fluminense",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 33,
      "W": 15,
      "D": 9,
      "L": 9,
      "GF": 52,
      "GA": 42,
      "GD": 10,
      "PTS": 54
     }
    },
    {
     "participantId": "soccer.athletico-paranaense",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 33,
      "W": 15,
      "D": 9,
      "L": 9,
      "GF": 50,
      "GA": 40,
      "GD": 10,
      "PTS": 54
     }
    },
    {
     "participantId": "soccer.bahia",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 33,
      "W": 14,
      "D": 11,
      "L": 8,
      "GF": 48,
      "GA": 42,
      "GD": 6,
      "PTS": 53
     }
    },
    {
     "participantId": "soccer.atletico-mg",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 33,
      "W": 14,
      "D": 8,
      "L": 11,
      "GF": 44,
      "GA": 39,
      "GD": 5,
      "PTS": 50
     }
    },
    {
     "participantId": "soccer.santos-2",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 33,
      "W": 12,
      "D": 11,
      "L": 10,
      "GF": 49,
      "GA": 47,
      "GD": 2,
      "PTS": 47
     }
    },
    {
     "participantId": "soccer.red-bull-bragantino",
     "participantType": "team",
     "rank": 9,
     "stats": {
      "GP": 33,
      "W": 12,
      "D": 8,
      "L": 13,
      "GF": 42,
      "GA": 38,
      "GD": 4,
      "PTS": 44
     }
    },
    {
     "participantId": "soccer.sao-paulo",
     "participantType": "team",
     "rank": 10,
     "stats": {
      "GP": 33,
      "W": 12,
      "D": 7,
      "L": 14,
      "GF": 39,
      "GA": 39,
      "GD": 0,
      "PTS": 43
     }
    },
    {
     "participantId": "soccer.botafogo",
     "participantType": "team",
     "rank": 11,
     "stats": {
      "GP": 33,
      "W": 10,
      "D": 9,
      "L": 14,
      "GF": 45,
      "GA": 53,
      "GD": -8,
      "PTS": 39
     }
    },
    {
     "participantId": "soccer.coritiba",
     "participantType": "team",
     "rank": 12,
     "stats": {
      "GP": 32,
      "W": 10,
      "D": 9,
      "L": 13,
      "GF": 38,
      "GA": 50,
      "GD": -12,
      "PTS": 39
     }
    },
    {
     "participantId": "soccer.vasco-da-gama",
     "participantType": "team",
     "rank": 13,
     "stats": {
      "GP": 32,
      "W": 10,
      "D": 8,
      "L": 14,
      "GF": 40,
      "GA": 49,
      "GD": -9,
      "PTS": 38
     }
    },
    {
     "participantId": "soccer.vitoria",
     "participantType": "team",
     "rank": 14,
     "stats": {
      "GP": 32,
      "W": 10,
      "D": 8,
      "L": 14,
      "GF": 35,
      "GA": 46,
      "GD": -11,
      "PTS": 38
     }
    },
    {
     "participantId": "soccer.gremio",
     "participantType": "team",
     "rank": 15,
     "stats": {
      "GP": 33,
      "W": 9,
      "D": 10,
      "L": 14,
      "GF": 37,
      "GA": 44,
      "GD": -7,
      "PTS": 37
     }
    },
    {
     "participantId": "soccer.mirassol",
     "participantType": "team",
     "rank": 16,
     "stats": {
      "GP": 33,
      "W": 9,
      "D": 10,
      "L": 14,
      "GF": 37,
      "GA": 47,
      "GD": -10,
      "PTS": 37
     }
    },
    {
     "participantId": "soccer.corinthians",
     "participantType": "team",
     "rank": 17,
     "stats": {
      "GP": 33,
      "W": 9,
      "D": 9,
      "L": 15,
      "GF": 36,
      "GA": 42,
      "GD": -6,
      "PTS": 36
     }
    },
    {
     "participantId": "soccer.internacional",
     "participantType": "team",
     "rank": 18,
     "stats": {
      "GP": 33,
      "W": 8,
      "D": 11,
      "L": 14,
      "GF": 37,
      "GA": 42,
      "GD": -5,
      "PTS": 35
     }
    },
    {
     "participantId": "soccer.remo",
     "participantType": "team",
     "rank": 19,
     "stats": {
      "GP": 33,
      "W": 6,
      "D": 11,
      "L": 16,
      "GF": 36,
      "GA": 51,
      "GD": -15,
      "PTS": 29
     }
    },
    {
     "participantId": "soccer.chapecoense",
     "participantType": "team",
     "rank": 20,
     "stats": {
      "GP": 32,
      "W": 4,
      "D": 9,
      "L": 19,
      "GF": 32,
      "GA": 66,
      "GD": -34,
      "PTS": 21
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.lvbp/seasons/2025-26/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.lvbp:2025-26",
 "updatedAt": "2026-10-03T18:04:32Z",
 "sources": [
  "mlb-statsapi"
 ],
 "competitionId": "baseball.lvbp",
 "season": "2025-26",
 "groups": [
  {
   "id": "135",
   "name": "Liga Venezolana de Béisbol Profesional (LVBP)",
   "rows": [
    {
     "participantId": "baseball.cardenales-de-lara",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 56,
      "W": 30,
      "L": 26,
      "PCT": 0.536,
      "STRK": "L1",
      "L10": "6-4",
      "HOME": "16-12",
      "AWAY": "14-14",
      "RS": 352,
      "RA": 307,
      "RD": 45
     },
     "extra": {
      "clinchIndicator": "@",
      "leagueRank": "1"
     }
    },
    {
     "participantId": "baseball.bravos-de-margarita",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 56,
      "W": 29,
      "L": 27,
      "PCT": 0.518,
      "STRK": "L6",
      "L10": "3-7",
      "HOME": "16-12",
      "AWAY": "13-15",
      "RS": 308,
      "RA": 295,
      "RD": 13
     },
     "extra": {
      "clinchIndicator": "@",
      "leagueRank": "2"
     }
    },
    {
     "participantId": "baseball.navegantes-del-magallanes",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 56,
      "W": 29,
      "L": 27,
      "PCT": 0.518,
      "STRK": "W3",
      "L10": "7-3",
      "HOME": "18-10",
      "AWAY": "11-17",
      "RS": 309,
      "RA": 277,
      "RD": 32
     },
     "extra": {
      "clinchIndicator": "@",
      "leagueRank": "3"
     }
    },
    {
     "participantId": "baseball.aguilas-del-zulia",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 56,
      "W": 29,
      "L": 27,
      "PCT": 0.518,
      "STRK": "W1",
      "L10": "6-4",
      "HOME": "16-12",
      "AWAY": "13-15",
      "RS": 261,
      "RA": 337,
      "RD": -76
     },
     "extra": {
      "clinchIndicator": "@",
      "leagueRank": "4"
     }
    },
    {
     "participantId": "baseball.caribes-de-anzoategui",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 56,
      "W": 28,
      "L": 28,
      "PCT": 0.5,
      "STRK": "L1",
      "L10": "4-6",
      "HOME": "18-10",
      "AWAY": "10-18",
      "RS": 349,
      "RA": 326,
      "RD": 23
     },
     "extra": {
      "clinchIndicator": "@",
      "leagueRank": "5"
     }
    },
    {
     "participantId": "baseball.tigres-de-aragua",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 56,
      "W": 28,
      "L": 28,
      "PCT": 0.5,
      "STRK": "W3",
      "L10": "4-6",
      "HOME": "19-9",
      "AWAY": "9-19",
      "RS": 282,
      "RA": 280,
      "RD": 2
     },
     "extra": {
      "clinchIndicator": "&",
      "leagueRank": "6"
     }
    },
    {
     "participantId": "baseball.tiburones-de-la-guaira",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 56,
      "W": 27,
      "L": 29,
      "PCT": 0.482,
      "STRK": "W1",
      "L10": "5-5",
      "HOME": "14-14",
      "AWAY": "13-15",
      "RS": 318,
      "RA": 320,
      "RD": -2
     },
     "extra": {
      "leagueRank": "7"
     }
    },
    {
     "participantId": "baseball.leones-del-caracas",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 56,
      "W": 24,
      "L": 32,
      "PCT": 0.429,
      "STRK": "L2",
      "L10": "3-7",
      "HOME": "14-14",
      "AWAY": "10-18",
      "RS": 319,
      "RA": 356,
      "RD": -37
     },
     "extra": {
      "leagueRank": "8"
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/soccer.tur-1/seasons/2026-27/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "soccer.tur-1:2026-27",
 "updatedAt": "2026-10-25T16:20:17Z",
 "sources": [
  "espn"
 ],
 "competitionId": "soccer.tur-1",
 "season": "2026-27",
 "groups": [
  {
   "id": "1",
   "name": "2026/2027 Turkish Super Lig",
   "rows": [
    {
     "participantId": "soccer.amed-sfk",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 9,
      "W": 6,
      "D": 2,
      "L": 1,
      "GF": 20,
      "GA": 10,
      "GD": 10,
      "PTS": 20
     },
     "extra": {
      "note": {
       "text": "Champions League",
       "color": "#81D6AC"
      }
     }
    },
    {
     "participantId": "soccer.galatasaray",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 8,
      "W": 6,
      "D": 1,
      "L": 1,
      "GF": 17,
      "GA": 11,
      "GD": 6,
      "PTS": 19
     },
     "extra": {
      "note": {
       "text": "Champions League qualifying",
       "color": "#B5E7CE"
      }
     }
    },
    {
     "participantId": "soccer.fenerbahce",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 8,
      "W": 5,
      "D": 1,
      "L": 2,
      "GF": 22,
      "GA": 6,
      "GD": 16,
      "PTS": 16
     },
     "extra": {
      "note": {
       "text": "Europa League qualifying",
       "color": "#B2BFD0"
      }
     }
    },
    {
     "participantId": "soccer.trabzonspor",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 8,
      "W": 5,
      "D": 1,
      "L": 2,
      "GF": 18,
      "GA": 5,
      "GD": 13,
      "PTS": 16
     },
     "extra": {
      "note": {
       "text": "Conference League qualifying",
       "color": "#c6d1e0"
      }
     }
    },
    {
     "participantId": "soccer.kasimpasa",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 9,
      "W": 4,
      "D": 4,
      "L": 1,
      "GF": 13,
      "GA": 9,
      "GD": 4,
      "PTS": 16
     }
    },
    {
     "participantId": "soccer.besiktas",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 8,
      "W": 5,
      "D": 0,
      "L": 3,
      "GF": 16,
      "GA": 10,
      "GD": 6,
      "PTS": 15
     }
    },
    {
     "participantId": "soccer.kocaelispor",
     "participantType": "team",
     "rank": 7,
     "stats": {
      "GP": 9,
      "W": 5,
      "D": 0,
      "L": 4,
      "GF": 11,
      "GA": 9,
      "GD": 2,
      "PTS": 15
     }
    },
    {
     "participantId": "soccer.erzurum-bb",
     "participantType": "team",
     "rank": 8,
     "stats": {
      "GP": 9,
      "W": 4,
      "D": 2,
      "L": 3,
      "GF": 8,
      "GA": 12,
      "GD": -4,
      "PTS": 14
     }
    },
    {
     "participantId": "soccer.corum-fk",
     "participantType": "team",
     "rank": 9,
     "stats": {
      "GP": 8,
      "W": 4,
      "D": 1,
      "L": 3,
      "GF": 18,
      "GA": 13,
      "GD": 5,
      "PTS": 13
     }
    },
    {
     "participantId": "soccer.alanyaspor",
     "participantType": "team",
     "rank": 10,
     "stats": {
      "GP": 9,
      "W": 3,
      "D": 3,
      "L": 3,
      "GF": 9,
      "GA": 11,
      "GD": -2,
      "PTS": 12
     }
    },
    {
     "participantId": "soccer.istanbul-basaksehir",
     "participantType": "team",
     "rank": 11,
     "stats": {
      "GP": 8,
      "W": 3,
      "D": 2,
      "L": 3,
      "GF": 12,
      "GA": 12,
      "GD": 0,
      "PTS": 11
     }
    },
    {
     "participantId": "soccer.caykur-rizespor",
     "participantType": "team",
     "rank": 12,
     "stats": {
      "GP": 8,
      "W": 3,
      "D": 1,
      "L": 4,
      "GF": 8,
      "GA": 11,
      "GD": -3,
      "PTS": 10
     }
    },
    {
     "participantId": "soccer.goztepe",
     "participantType": "team",
     "rank": 13,
     "stats": {
      "GP": 8,
      "W": 2,
      "D": 3,
      "L": 3,
      "GF": 17,
      "GA": 16,
      "GD": 1,
      "PTS": 9
     }
    },
    {
     "participantId": "soccer.konyaspor",
     "participantType": "team",
     "rank": 14,
     "stats": {
      "GP": 9,
      "W": 2,
      "D": 2,
      "L": 5,
      "GF": 6,
      "GA": 9,
      "GD": -3,
      "PTS": 8
     }
    },
    {
     "participantId": "soccer.gaziantep-fk",
     "participantType": "team",
     "rank": 15,
     "stats": {
      "GP": 9,
      "W": 2,
      "D": 2,
      "L": 5,
      "GF": 9,
      "GA": 15,
      "GD": -6,
      "PTS": 8
     }
    },
    {
     "participantId": "soccer.genclerbirligi",
     "participantType": "team",
     "rank": 16,
     "stats": {
      "GP": 9,
      "W": 2,
      "D": 2,
      "L": 5,
      "GF": 7,
      "GA": 18,
      "GD": -11,
      "PTS": 8
     },
     "extra": {
      "note": {
       "text": "Relegated",
       "color": "#FF7F84"
      }
     }
    },
    {
     "participantId": "soccer.samsunspor",
     "participantType": "team",
     "rank": 17,
     "stats": {
      "GP": 9,
      "W": 1,
      "D": 1,
      "L": 7,
      "GF": 8,
      "GA": 21,
      "GD": -13,
      "PTS": 4
     },
     "extra": {
      "note": {
       "text": "Relegated",
       "color": "#FF7F84"
      }
     }
    },
    {
     "participantId": "soccer.eyupspor",
     "participantType": "team",
     "rank": 18,
     "stats": {
      "GP": 9,
      "W": 1,
      "D": 0,
      "L": 8,
      "GF": 2,
      "GA": 23,
      "GD": -21,
      "PTS": 3
     },
     "extra": {
      "note": {
       "text": "Relegated",
       "color": "#FF7F84"
      }
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.serie-del-caribe/seasons/2024-25/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.serie-del-caribe:2024-25",
 "updatedAt": "2026-10-03T18:05:53Z",
 "sources": [
  "mlb-statsapi"
 ],
 "competitionId": "baseball.serie-del-caribe",
 "season": "2024-25",
 "groups": [
  {
   "id": "162",
   "name": "Serie del Caribe",
   "rows": [
    {
     "participantId": "baseball.mexico-rojo",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 6,
      "W": 5,
      "L": 1,
      "PCT": 0.833,
      "STRK": "L1",
      "L10": "5-1",
      "HOME": "3-1",
      "AWAY": "2-0",
      "RS": 22,
      "RA": 6,
      "RD": 16
     },
     "extra": {
      "leagueRank": "1"
     }
    },
    {
     "participantId": "baseball.dominican-republic",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 6,
      "W": 4,
      "L": 2,
      "PCT": 0.667,
      "STRK": "W2",
      "L10": "4-2",
      "HOME": "1-1",
      "AWAY": "3-1",
      "RS": 27,
      "RA": 17,
      "RD": 10
     },
     "extra": {
      "leagueRank": "2"
     }
    },
    {
     "participantId": "baseball.puerto-rico",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 6,
      "W": 3,
      "L": 3,
      "PCT": 0.5,
      "STRK": "W1",
      "L10": "3-3",
      "HOME": "1-1",
      "AWAY": "2-2",
      "RS": 27,
      "RA": 34,
      "RD": -7
     },
     "extra": {
      "leagueRank": "3"
     }
    },
    {
     "participantId": "baseball.venezuela",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 6,
      "W": 2,
      "L": 4,
      "PCT": 0.333,
      "STRK": "L2",
      "L10": "2-4",
      "HOME": "1-3",
      "AWAY": "1-1",
      "RS": 29,
      "RA": 21,
      "RD": 8
     },
     "extra": {
      "leagueRank": "4"
     }
    },
    {
     "participantId": "baseball.japan",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 4,
      "W": 0,
      "L": 4,
      "PCT": 0.0,
      "STRK": "L4",
      "L10": "0-4",
      "HOME": "0-2",
      "AWAY": "0-2",
      "RS": 5,
      "RA": 32,
      "RD": -27
     },
     "extra": {
      "leagueRank": "5"
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.lpb-colombia/seasons/2025-26/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.lpb-colombia:2025-26",
 "updatedAt": "2026-10-03T18:07:05Z",
 "sources": [
  "lpbcol"
 ],
 "competitionId": "baseball.lpb-colombia",
 "season": "2025-26",
 "groups": [
  {
   "id": "all",
   "name": "Temporada regular",
   "rows": [
    {
     "participantId": "baseball.caimanes",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "W": 19,
      "L": 11,
      "T": 0,
      "PCT": 0.633,
      "GB": 0.0
     }
    },
    {
     "participantId": "baseball.tigres",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "W": 16,
      "L": 14,
      "T": 0,
      "PCT": 0.533,
      "GB": 3.0
     }
    },
    {
     "participantId": "baseball.vaqueros",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "W": 16,
      "L": 14,
      "T": 0,
      "PCT": 0.533,
      "GB": 3.0
     }
    },
    {
     "participantId": "baseball.toros",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "W": 9,
      "L": 21,
      "T": 0,
      "PCT": 0.3,
      "GB": 10.0
     }
    }
   ]
  }
 ]
}

=== jcmachadoh/cuba-deportes-data/data/v1/competitions/baseball.lbprc/seasons/2024-25/standings.json
{
 "schemaVersion": 1,
 "type": "standings",
 "id": "baseball.lbprc:2024-25",
 "updatedAt": "2026-10-03T18:05:34Z",
 "sources": [
  "mlb-statsapi"
 ],
 "competitionId": "baseball.lbprc",
 "season": "2024-25",
 "groups": [
  {
   "id": "133",
   "name": "Liga de Béisbol Profesional Roberto Clemente (Puerto Rico)",
   "rows": [
    {
     "participantId": "baseball.indios-de-mayaguez",
     "participantType": "team",
     "rank": 1,
     "stats": {
      "GP": 40,
      "W": 24,
      "L": 16,
      "PCT": 0.6,
      "GB": -5.0,
      "STRK": "W1",
      "L10": "6-4",
      "HOME": "15-5",
      "AWAY": "9-11",
      "RS": 170,
      "RA": 134,
      "RD": 36
     },
     "extra": {
      "leagueRank": "1"
     }
    },
    {
     "participantId": "baseball.cangrejeros-de-santurce",
     "participantType": "team",
     "rank": 2,
     "stats": {
      "GP": 40,
      "W": 21,
      "L": 19,
      "PCT": 0.525,
      "GB": -2.0,
      "STRK": "L1",
      "L10": "6-4",
      "HOME": "12-8",
      "AWAY": "9-11",
      "RS": 158,
      "RA": 121,
      "RD": 37
     },
     "extra": {
      "leagueRank": "2"
     }
    },
    {
     "participantId": "baseball.senadores-de-san-juan",
     "participantType": "team",
     "rank": 3,
     "stats": {
      "GP": 40,
      "W": 21,
      "L": 19,
      "PCT": 0.525,
      "GB": -2.0,
      "STRK": "L1",
      "L10": "4-6",
      "HOME": "11-9",
      "AWAY": "10-10",
      "RS": 142,
      "RA": 163,
      "RD": -21
     },
     "extra": {
      "leagueRank": "3"
     }
    },
    {
     "participantId": "baseball.criollos-de-caguas",
     "participantType": "team",
     "rank": 4,
     "stats": {
      "GP": 40,
      "W": 19,
      "L": 21,
      "PCT": 0.475,
      "STRK": "W1",
      "L10": "6-4",
      "HOME": "8-12",
      "AWAY": "11-9",
      "RS": 158,
      "RA": 137,
      "RD": 21
     },
     "extra": {
      "leagueRank": "4"
     }
    },
    {
     "participantId": "baseball.leones-de-ponce",
     "participantType": "team",
     "rank": 5,
     "stats": {
      "GP": 40,
      "W": 18,
      "L": 22,
      "PCT": 0.45,
      "GB": 1.0,
      "STRK": "W1",
      "L10": "4-6",
      "HOME": "9-11",
      "AWAY": "9-11",
      "RS": 143,
      "RA": 179,
      "RD": -36
     },
     "extra": {
      "leagueRank": "5"
     }
    },
    {
     "participantId": "baseball.gigantes-de-carolina",
     "participantType": "team",
     "rank": 6,
     "stats": {
      "GP": 40,
      "W": 17,
      "L": 23,
      "PCT": 0.425,
      "GB": 2.0,
      "STRK": "L1",
      "L10": "4-6",
      "HOME": "8-12",
      "AWAY": "9-11",
      "RS": 136,
      "RA": 173,
      "RD": -37
     },
     "extra": {
      "leagueRank": "6"
     }
    }
   ]
  }
 ]
}
